# Generated by Django 4.1.4 on 2022-12-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField()),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Madculino"), ("F", "Femenino")], max_length=100
                    ),
                ),
                ("estado", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_bautismo", models.DateField()),
            ],
        ),
    ]
